/*
 * Minitwit API
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System.ComponentModel.DataAnnotations;
using System.Globalization;
using System.Text;
using Chirp.Application.DTO;
using Chirp.Application.Services.Interface;
using Chirp.Core.Models;
using Chirp.Core.Repositories;
using Chirp.Web.Attributes;
using Swashbuckle.AspNetCore.Annotations;
using Chirp.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.VisualBasic;
using Newtonsoft.Json;

namespace Chirp.Web.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    [Authorize(AuthenticationSchemes = "BasicAuthentication", Policy = "ApiPolicy")]
    public class MinitwitApiController : ControllerBase
    { 
        
        private const string ExpectedCaller = "simulator";
        private const string ExpectedCallerPassword = "super_safe!";
        private const int DefaultPageSize = 100;
        private readonly ICheepService _cheepService;
        private readonly IAuthorService _authorService;
        private readonly UserManager<Author> _userManager;

        public MinitwitApiController(
            ICheepService cheepService,
            IAuthorService authorService,
            UserManager<Author> userManager)
        {
            _userManager = userManager;
            _cheepService = cheepService;
            _authorService = authorService;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Get list of users followed by the given user.  - Query param &#x60;?no&#x3D;&#x60; limits result count. - Optionally updates a &#39;latest&#39; global value via &#x60;?latest&#x3D;&#x60; query param.</remarks>
        /// <param name="username"></param>
        /// <param name="authorization">Authorization string of the form &#x60;Basic c2ltdWxhdG9yOnN1cGVyX3NhZmUh&#x60;. Used to authenticate as simulator</param>
        /// <param name="latest">Optional: &#x60;latest&#x60; value to update</param>
        /// <param name="no">Optional: &#x60;no&#x60; limits result count</param>
        /// <response code="200">Success</response>
        /// <response code="403">Unauthorized - Must include correct Authorization header</response>
        /// <response code="404">User not found (no response body)</response>
        [HttpGet]
        [Route("/fllws/{username}")]
        [ValidateModelState]
        [SwaggerOperation("GetFollow")]
        [SwaggerResponse(statusCode: 200, type: typeof(FollowsResponse), description: "Success")]
        [SwaggerResponse(statusCode: 403, type: typeof(ErrorResponse), description: "Unauthorized - Must include correct Authorization header")]
        [SwaggerResponse(statusCode: 404, type: typeof(ErrorResponse), description: "Nothing here - No user with this name has been found")]
        public virtual IActionResult GetFollow([FromRoute (Name = "username")][Required]string username, [FromHeader (Name = "Authorization")][Required()]string authorization, [FromQuery (Name = "latest")]int? latest, [FromQuery (Name = "no")]int? no)
        {
            var author = _authorService.FindAuthorByUsername(username);
            if (author == null)
            {
                return BadRequest(new ErrorResponse
                {
                    ErrorMsg = "Missing author",
                    Status = 400
                });
            }

            var followers = _authorService
                .GetFollowing(author.Id)
                .Select(f => f?.Name)
                .ToList();
            
            return Ok(followers);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Returns the latest ID saved</remarks>
        /// <response code="200">Success</response>
        /// <response code="500">Internal Server Error</response>
        [HttpGet]
        [Route("/latest")]
        [ValidateModelState]
        [SwaggerOperation("GetLatestValue")]
        [SwaggerResponse(statusCode: 200, type: typeof(LatestValue), description: "Success")]
        [SwaggerResponse(statusCode: 500, type: typeof(ErrorResponse), description: "Internal Server Error")]
        public virtual IActionResult GetLatestValue()
        {
            var latestCheep = _cheepService
                .GetCheeps(1, 1)
                .FirstOrDefault();
            var latestId = latestCheep?.cheepId;
            return Ok(new LatestValue { Latest = latestId });
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Get recent messages.  - Filters out flagged messages - Returns a list of recent messages (max defined by &#x60;?no&#x3D;&#x60; param) - Optionally updates a &#39;latest&#39; global value via &#x60;?latest&#x3D;&#x60; query param.</remarks>
        /// <param name="authorization">Authorization string of the form &#x60;Basic c2ltdWxhdG9yOnN1cGVyX3NhZmUh&#x60;. Used to authenticate as simulator</param>
        /// <param name="latest">Optional: &#x60;latest&#x60; value to update</param>
        /// <param name="no">Optional: &#x60;no&#x60; limits result count</param>
        /// <response code="200">Success</response>
        /// <response code="403">Unauthorized - Must include correct Authorization header</response>
        [HttpGet]
        [Route("/msgs")]
        [ValidateModelState]
        [SwaggerOperation("GetMessages")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<Message>), description: "Success")]
        [SwaggerResponse(statusCode: 403, type: typeof(ErrorResponse), description: "Unauthorized - Must include correct Authorization header")]
        public virtual IActionResult GetMessages([FromHeader (Name = "Authorization")][Required()]string authorization, [FromQuery (Name = "latest")]int? latest, [FromQuery (Name = "no")]int? no)
        {
            var limit = no is > 0 ? no.Value : DefaultPageSize;
            var messages = _cheepService
                .GetCheeps(1, limit)
                .Select(MapCheepToMessage)
                .ToList();
            return Ok(messages);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Get messages for a specific user.  - Returns messages authored by the specified user - Filtered by unflagged - Returns a list of recent messages for the user (max defined by &#x60;?no&#x3D;&#x60; param) - Optionally updates a &#39;latest&#39; global value via &#x60;?latest&#x3D;&#x60; query param.</remarks>
        /// <param name="username"></param>
        /// <param name="authorization">Authorization string of the form &#x60;Basic c2ltdWxhdG9yOnN1cGVyX3NhZmUh&#x60;. Used to authenticate as simulator</param>
        /// <param name="latest">Optional: &#x60;latest&#x60; value to update</param>
        /// <param name="no">Optional: &#x60;no&#x60; limits result count</param>
        /// <response code="200">Success</response>
        /// <response code="403">Unauthorized - Must include correct Authorization header</response>
        /// <response code="404">User not found (no response body)</response>
        [HttpGet]
        [Route("/msgs/{username}")]
        [ValidateModelState]
        [SwaggerOperation("GetMessagesPerUser")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<Message>), description: "Success")]
        [SwaggerResponse(statusCode: 403, type: typeof(ErrorResponse), description: "Unauthorized - Must include correct Authorization header")]
        public virtual IActionResult GetMessagesPerUser([FromRoute (Name = "username")][Required]string username, [FromHeader (Name = "Authorization")][Required()]string authorization, [FromQuery (Name = "latest")]int? latest, [FromQuery (Name = "no")]int? no)
        {
            var author =  _authorService.FindAuthorByUsername(username);
            if (author == null)
            {
                return BadRequest(new ErrorResponse
                {
                    ErrorMsg = "Missing author",
                    Status = 400
                });
            }
            
            var messages = _cheepService
                .GetCheepsFromAuthorId(author.Id)
                .Select(MapCheepToMessage)
                .ToList();
            return Ok(messages);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Follow or unfollow a user on behalf of &#x60;username&#x60;.  - Body must contain either &#x60;follow: &lt;user&gt;&#x60; or &#x60;unfollow: &lt;user&gt;&#x60;</remarks>
        /// <param name="username"></param>
        /// <param name="authorization">Authorization string of the form &#x60;Basic c2ltdWxhdG9yOnN1cGVyX3NhZmUh&#x60;. Used to authenticate as simulator</param>
        /// <param name="payload"></param>
        /// <param name="latest">Optional: &#x60;latest&#x60; value to update</param>
        /// <response code="204">No Content</response>
        /// <response code="403">Unauthorized - Must include correct Authorization header</response>
        /// <response code="404">User not found (no response body)</response>
        [HttpPost]
        [Route("/fllws/{username}")]
        [Consumes("application/json")]
        [ValidateModelState]
        [SwaggerOperation("PostFollow")]
        [SwaggerResponse(statusCode: 403, type: typeof(ErrorResponse), description: "Unauthorized - Must include correct Authorization header")]
        public virtual IActionResult PostFollow([FromRoute (Name = "username")][Required]string username, [FromHeader (Name = "Authorization")][Required()]string authorization, [FromBody]FollowAction payload, [FromQuery (Name = "latest")]int? latest)
        {
            if (payload == null) 
            {
                return NotFound(new ErrorResponse
                {
                    ErrorMsg = "User not found",
                    Status = 404
                });
            }
            
            var author = _authorService.FindAuthorByUsername(username);
            if (author == null)
            {
                return BadRequest(new ErrorResponse
                {
                    ErrorMsg = "Missing author",
                    Status = 400
                });
            }

            var hasFollow = !string.IsNullOrWhiteSpace(payload?.Follow);
            var hasUnfollow = !string.IsNullOrWhiteSpace(payload?.Unfollow);

            if (hasFollow && hasUnfollow) 
            {
                return BadRequest(new ErrorResponse
                {
                    ErrorMsg = "Both follow and unfollow request sent.",
                    Status = 400
                });
            }
            
            //follow logic
            if (hasFollow)
            {
                var followee = _authorService.FindAuthorByUsername(payload?.Follow);
                if (followee == null)
                {
                    return BadRequest(new ErrorResponse
                    {
                        ErrorMsg = "Missing followee",
                        Status = 400
                    });
                }
                _authorService.FollowAuthor(author.Id, followee.Id);
                return NoContent();
            }
            
            //Unfollow logic
            if (hasUnfollow)
            {
                var followee = _authorService.FindAuthorByUsername(payload?.Unfollow);
                if (followee == null)
                {
                    return BadRequest(new ErrorResponse
                    {
                        ErrorMsg = "Missing followee",
                        Status = 400
                    });
                }
                
                _authorService.UnfollowAuthor(author.Id, followee.Id);
                return NoContent();
            }
            
            return BadRequest();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Post a new message as a specific user.  - Message must include &#x60;content&#x60; in the body - Stored with timestamp and &#x60;flagged&#x3D;0&#x60; - Returns empty body on success - Optionally updates a &#39;latest&#39; global value via &#x60;?latest&#x3D;&#x60; query param.</remarks>
        /// <param name="username"></param>
        /// <param name="authorization">Authorization string of the form &#x60;Basic c2ltdWxhdG9yOnN1cGVyX3NhZmUh&#x60;. Used to authenticate as simulator</param>
        /// <param name="payload"></param>
        /// <param name="latest">Optional: &#x60;latest&#x60; value to update</param>
        /// <response code="204">No Content</response>
        /// <response code="403">Unauthorized - Must include correct Authorization header</response>
        [HttpPost]
        [Route("/msgs/{username}")]
        [Consumes("application/json")]
        [ValidateModelState]
        [SwaggerOperation("PostMessagesPerUser")]
        [SwaggerResponse(statusCode: 403, type: typeof(ErrorResponse), description: "Unauthorized - Must include correct Authorization header")]
        public virtual IActionResult PostMessagesPerUser([FromRoute (Name = "username")][Required]string username, [FromHeader (Name = "Authorization")][Required()]string authorization, [FromBody]PostMessage payload, [FromQuery (Name = "latest")]int? latest)
        {
            var author = _authorService.FindAuthorByUsername(username);
            
            if (author == null)
            {
                return BadRequest(new ErrorResponse
                {
                    ErrorMsg = "Missing author",
                    Status = 400
                });
            }

            if (payload == null)
            {
                return BadRequest(new ErrorResponse
                {
                    ErrorMsg = "Missing content in payload",
                    Status = 404
                });
            }
            
            _cheepService.AddCheep(payload.Content, author.Id);
            return StatusCode(200);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Register a new user. - Optionally updates a &#39;latest&#39; global value via &#x60;?latest&#x3D;&#x60; query param.</remarks>
        /// <param name="payload"></param>
        /// <param name="latest">Optional: &#x60;latest&#x60; value to update</param>
        /// <response code="204">No Content</response>
        /// <response code="400">Bad Request | Possible reasons:  - missing username  - invalid email  - password missing  - username already taken</response>
        [HttpPost]
        [Route("/register")]
        [Consumes("application/json")]
        [ValidateModelState]
        [SwaggerOperation("PostRegister")]
        [SwaggerResponse(statusCode: 400, type: typeof(ErrorResponse), description: "Bad Request | Possible reasons:  - missing username  - invalid email  - password missing  - username already taken")]
        public virtual IActionResult PostRegister([FromBody]RegisterRequest payload, [FromQuery (Name = "latest")]int? latest)
        {
            
            if (string.IsNullOrWhiteSpace(payload.Username))
            {
                return BadRequest(new ErrorResponse
                {
                    ErrorMsg = "Missing username",
                    Status = 400
                });
            }
            
            if (string.IsNullOrWhiteSpace(payload.Pwd))
            {
                return BadRequest(new ErrorResponse
                {
                    ErrorMsg = "Missing Password",
                    Status = 400
                });
            }

            if (string.IsNullOrWhiteSpace(payload.Email))
            {
                return BadRequest(new ErrorResponse
                {
                    ErrorMsg = "Missing Email",
                    Status = 400
                });
            }
            
            AuthorDTO? author = _authorService.FindAuthorByUsername(payload.Username);
            
            if (author != null) {
                
                return BadRequest(new ErrorResponse
                {
                    ErrorMsg = "username already taken",
                    Status = 400
                });
            }
            
            author = _authorService.FindAuthorByEmail(payload.Email);
            
            if (author != null) {
                
                return BadRequest(new ErrorResponse
                {
                    ErrorMsg = "invalid email",
                    Status = 400
                });
            }

            Author newAuthor = new Author
            {
                Name = payload.Username,
                UserName = payload.Username,
                Email = payload.Email
            };
            
            var result = _userManager.CreateAsync(newAuthor, payload.Pwd).GetAwaiter().GetResult();

            if (!result.Succeeded)
            {
                foreach (var error in result.Errors)
                {
                    Console.WriteLine($"IDENTITY ERROR: {error.Description}");
                }

                return BadRequest(result.Errors);
            }

            return NoContent();
        }

        private static Message MapCheepToMessage(CheepDTO cheep)
        {
            return new Message
            {
                Content = cheep.Message,
                User = cheep.Author,
                PubDate = cheep.CreatedDate,
            };
        }
    }
}
