version: '3.3'

networks:
  main:

services:

  minitwit:
    image: itu-minitwit
    container_name: minitwit
    ports:
      - "5000:5000"
    environment:
      CHIRP_DB_CONNECTION: ${CHIRP_DB_CONNECTION}
  
  prometheus:
    build:
      dockerfile: ./Dockerfile
      context: ../Monitoring/prometheus
    image: prometheus_image
    container_name: Prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
  
  grafana:
    build:
      dockerfile: ./Dockerfile
      context: ../Monitoring/grafana/provisioning
    image: grafana_image
    container_name: grafana
    ports: 
      - "3000:3000"
    volumes: 
      - grafana-storage:/var/lib/grafana
      - ../Monitoring/grafana/provisioning:/etc/grafana/provisioning

volumes:
  grafana-storage: