events {}
http {
    upstream minitwit_backend {
        ip_hash;
        server minitwit:5000;
    }
    server {
        listen 80;
        location / {
            proxy_pass http://minitwit_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
