<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
	  <TargetFramework>net8.0</TargetFramework>
	  <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>5632450c-4f48-42aa-b1ed-915a0d2b7fef</UserSecretsId>
	  <PreserveCompilationContext>true</PreserveCompilationContext>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="wwwroot\images\Icon1.png" />
    <Content Remove="wwwroot\images\Thumps Down Grey.png" />
    <Content Remove="wwwroot\images\Thumps Down.png" />
    <Content Remove="wwwroot\images\Thumps Up Grey.png" />
    <Content Remove="wwwroot\images\Thumps Up.png" />
  </ItemGroup>

  <ItemGroup>
	<Folder Include="data\" />
	<Folder Include="wwwroot\profilePics\" />
	<PackageReference Include="AspNet.Security.OAuth.GitHub" Version="8.0.0" />
	<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.5">
	  <PrivateAssets>all</PrivateAssets>
	  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
	<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.5" />
	<PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.5" />
	<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.5" />
	<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.5">
	  <PrivateAssets>all</PrivateAssets>
	  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
	<PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.0" />
	<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
	<PackageReference Include="prometheus-net.AspNetCore" Version="8.2.1" />
	<PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="10.1.3" />
	<ProjectReference Include="..\Chirp.Core\Chirp.Core.csproj" />
	<ProjectReference Include="..\Chirp.Infrastructure\Chirp.Infrastructure.csproj" />
	<ProjectReference Include="..\Chirp.Application\Chirp.Application.csproj" />
	  <Folder Include="Areas\Identity\Data\" />	  
	  
	
  </ItemGroup></Project>
